CREATE DATABASE APTECH_SEM_3
USE APTECH_SEM_3
	BEGIN TRANSACTION;
		--USER
		CREATE TABLE USR(
			UID INT IDENTITY(1,1) PRIMARY KEY, --USER ID
			USERNAME VARCHAR(100) NOT NULL,
			PASSWORD VARCHAR(100) NOT NULL,
			NAME VARCHAR(100) NOT NULL,
			ADDRESS VARCHAR(100) NOT NULL,
			PHONE VARCHAR(100) NOT NULL,
			ROLE VARCHAR(50) NOT NULL,
			PHOTO VARCHAR(250) NOT NULL,
			SKILL TEXT NOT NULL,
			WORK_EXP TEXT NOT NULL --WORK EXPERIENCE
		)	
		CREATE TABLE TEST(
			UID INT  NOT NULL,
			START_TIME DATETIME  NOT NULL,
			END_TIME DATETIME  NOT NULL,
			TID INT IDENTITY(1,1) PRIMARY KEY --TEST ID
		)
		CREATE TABLE TEST_QUESTION(
			TID INT  NOT NULL, --TEST ID
			QID INT  NOT NULL  --QUESTION ID
		)
		ALTER TABLE TEST_QUESTION ADD PRIMARY KEY(TID,QID)
		CREATE TABLE QUESTION(
			QID INT IDENTITY (1,1) PRIMARY KEY,
			QUESTION TEXT  NOT NULL
		)	
		CREATE TABLE ANSWER(
			AID INT IDENTITY(1,1) PRIMARY KEY,
			QID INT  NOT NULL,
			ANSWER TEXT  NOT NULL,
			STATUS BIT  NOT NULL
		)
		CREATE TABLE TEST_CANDIDATE(
			UID INT NOT NULL,
			TID INT NOT NULL,
			RESULT_SCORE INT ,
			RESULT_TIME TIME,
			ATTEMPT_STATUS BIT NOT NULL
		)
		CREATE TABLE JOB_POST(
			PID INT IDENTITY(1,1) PRIMARY KEY, --POST ID
			CREATED DATETIME  NOT NULL,
			POST TEXT  NOT NULL
		)
		CREATE TABLE JOB_APPLICATION(
			PID INT NOT NULL,
			UID INT NOT NULL,
			CREATED DATETIME  NOT NULL
		)
		ALTER TABLE JOB_APPLICATION ADD PRIMARY KEY(PID,UID)
		CREATE TABLE RESULT(
			RESULT_NAME VARCHAR(100) PRIMARY KEY,
			PERCENT_HIGH_SCORE FLOAT NOT NULL,
			PERCENT_MIDDLE_SCORE FLOAT NOT NULL,
			PERCENT_LOW_SCORE FLOAT NOT NULL,
			PERCENT_ATTEMPT FLOAT NOT NULL,
			PERCENT_FAST_FINISH FLOAT NOT NULL,
			COMMENT TEXT
		)
	--LINK TABLE
		--TEST
		ALTER TABLE TEST ADD CONSTRAINT TEST_USR FOREIGN KEY (UID) REFERENCES USR(UID)
		--TEST_QUESTION
		ALTER TABLE TEST_QUESTION ADD CONSTRAINT TEST_QUESTION_TEST FOREIGN KEY (TID) REFERENCES TEST(TID)
		ALTER TABLE TEST_QUESTION ADD CONSTRAINT TEST_QUESTION_QUESTION FOREIGN KEY (QID) REFERENCES QUESTION(QID)
		--ANSER
		ALTER TABLE ANSWER ADD CONSTRAINT ANSWER_QUESTION FOREIGN KEY (QID) REFERENCES QUESTION(QID)
		--TEST CANDIDATE
		ALTER TABLE TEST_CANDIDATE ADD CONSTRAINT TEST_CANDIDATE_USR FOREIGN KEY (UID) REFERENCES USR(UID)
		ALTER TABLE TEST_CANDIDATE ADD CONSTRAINT TEST_CANDIDATE_TEST FOREIGN KEY (TID) REFERENCES TEST(TID)
		--JOB POST
		ALTER TABLE JOB_APPLICATION ADD CONSTRAINT JOB_APPLICATION_USR FOREIGN KEY (UID) REFERENCES USR(UID)
		ALTER TABLE JOB_APPLICATION ADD CONSTRAINT JOB_APPLICATION_POST FOREIGN KEY (PID) REFERENCES JOB_POST(PID)
	COMMIT;
	--ROLLBACK;

		