//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechSem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER
    {
        public int ANSWER_ID { get; set; }
        public int QUESTION_ID { get; set; }
        public string ANSWER1 { get; set; }
        public bool STATUS { get; set; }
    
        public virtual QUESTION QUESTION { get; set; }
    }
}
