//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechSem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_APPLICATION
    {
        public JOB_APPLICATION()
        {
            this.RESULTs = new HashSet<RESULT>();
            this.USRs = new HashSet<USR>();
        }
    
        public int APPLY_ID { get; set; }
        public int POST_ID { get; set; }
        public string PERSONAL_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EDUCATION { get; set; }
        public string WORK_EXP { get; set; }
        public System.DateTime CREATED { get; set; }
        public int APPROVE_STATUS { get; set; }
        public string MAIL { get; set; }
    
        public virtual JOB_POST JOB_POST { get; set; }
        public virtual ICollection<RESULT> RESULTs { get; set; }
        public virtual ICollection<USR> USRs { get; set; }
    }
}
