//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechSem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_POST
    {
        public JOB_POST()
        {
            this.JOB_APPLICATION = new HashSet<JOB_APPLICATION>();
            this.TESTs = new HashSet<TEST>();
        }
    
        public int POST_ID { get; set; }
        public System.DateTime CREATED { get; set; }
        public System.DateTime END_DATE { get; set; }
        public string POST { get; set; }
    
        public virtual ICollection<JOB_APPLICATION> JOB_APPLICATION { get; set; }
        public virtual ICollection<TEST> TESTs { get; set; }
    }
}
