//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechSem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public QUESTION()
        {
            this.ANSWERs = new HashSet<ANSWER>();
            this.TESTs = new HashSet<TEST>();
        }
    
        public string CATEGORY { get; set; }
        public int QUESTION_ID { get; set; }
        public string QUESTION1 { get; set; }
        public int POINT { get; set; }
    
        public virtual ICollection<ANSWER> ANSWERs { get; set; }
        public virtual ICollection<TEST> TESTs { get; set; }
    }
}
