//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechSem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public System.DateTime CREATED { get; set; }
        public double PERCENT_HIGH_SCORE { get; set; }
        public double PERCENT_MIDDLE_SCORE { get; set; }
        public double PERCENT_ATTEMPT { get; set; }
        public double PERCENT_FAST_FINISH { get; set; }
        public double PERCENT_HIGH_PART_1 { get; set; }
        public double PERCENT_MID_PART_1 { get; set; }
        public double PERCENT_HIGH_PART_2 { get; set; }
        public double PERCENT_MID_PART_2 { get; set; }
        public double PERCENT_HIGH_PART_3 { get; set; }
        public double PERCENT_MID_PART_3 { get; set; }
    }
}
