//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechSem3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class APTECH_SEM_3Entities : DbContext
    {
        public APTECH_SEM_3Entities()
            : base("name=APTECH_SEM_3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ANSWER> ANSWERs { get; set; }
        public DbSet<JOB_APPLICATION> JOB_APPLICATION { get; set; }
        public DbSet<JOB_POST> JOB_POST { get; set; }
        public DbSet<QUESTION> QUESTIONs { get; set; }
        public DbSet<REPORT> REPORTs { get; set; }
        public DbSet<RESULT> RESULTs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TEST> TESTs { get; set; }
        public DbSet<USR> USRs { get; set; }
    
        public virtual ObjectResult<Nullable<int>> FIND_QID_FROM_USERNAME(string uSERNAME)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("FIND_QID_FROM_USERNAME", uSERNAMEParameter);
        }
    }
}
