//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptechSem3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class APTECH_SEM_3Entities : DbContext
    {
        public APTECH_SEM_3Entities()
            : base("name=APTECH_SEM_3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ANSWER> ANSWERs { get; set; }
        public DbSet<JOB_APPLICATION> JOB_APPLICATION { get; set; }
        public DbSet<JOB_POST> JOB_POST { get; set; }
        public DbSet<QUESTION> QUESTIONs { get; set; }
        public DbSet<REPORT> REPORTs { get; set; }
        public DbSet<RESULT> RESULTs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TEST> TESTs { get; set; }
        public DbSet<USR> USRs { get; set; }
    
        public virtual ObjectResult<Nullable<int>> FIND_QID_FROM_USERNAME(string uSERNAME)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("FIND_QID_FROM_USERNAME", uSERNAMEParameter);
        }
    
        public virtual ObjectResult<FIND_QUESTION_WITH_TEST_Result> FIND_QUESTION_WITH_TEST(Nullable<int> tEST_ID)
        {
            var tEST_IDParameter = tEST_ID.HasValue ?
                new ObjectParameter("TEST_ID", tEST_ID) :
                new ObjectParameter("TEST_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FIND_QUESTION_WITH_TEST_Result>("FIND_QUESTION_WITH_TEST", tEST_IDParameter);
        }
    
        public virtual ObjectResult<FIND_USR_BY_TEST_END_Result> FIND_USR_BY_TEST_END(Nullable<System.DateTime> tIME1, Nullable<System.DateTime> tIME2)
        {
            var tIME1Parameter = tIME1.HasValue ?
                new ObjectParameter("TIME1", tIME1) :
                new ObjectParameter("TIME1", typeof(System.DateTime));
    
            var tIME2Parameter = tIME2.HasValue ?
                new ObjectParameter("TIME2", tIME2) :
                new ObjectParameter("TIME2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FIND_USR_BY_TEST_END_Result>("FIND_USR_BY_TEST_END", tIME1Parameter, tIME2Parameter);
        }
    
        public virtual ObjectResult<GET_1_RANDOM_QUESTION_Result> GET_1_RANDOM_QUESTION(string cATEGORY, Nullable<int> pOINT)
        {
            var cATEGORYParameter = cATEGORY != null ?
                new ObjectParameter("CATEGORY", cATEGORY) :
                new ObjectParameter("CATEGORY", typeof(string));
    
            var pOINTParameter = pOINT.HasValue ?
                new ObjectParameter("POINT", pOINT) :
                new ObjectParameter("POINT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_1_RANDOM_QUESTION_Result>("GET_1_RANDOM_QUESTION", cATEGORYParameter, pOINTParameter);
        }
    
        public virtual ObjectResult<GET_2_RANDOM_QUESTIONS_Result> GET_2_RANDOM_QUESTIONS(string cATEGORY, Nullable<int> pOINT)
        {
            var cATEGORYParameter = cATEGORY != null ?
                new ObjectParameter("CATEGORY", cATEGORY) :
                new ObjectParameter("CATEGORY", typeof(string));
    
            var pOINTParameter = pOINT.HasValue ?
                new ObjectParameter("POINT", pOINT) :
                new ObjectParameter("POINT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_2_RANDOM_QUESTIONS_Result>("GET_2_RANDOM_QUESTIONS", cATEGORYParameter, pOINTParameter);
        }
    
        public virtual ObjectResult<GET_LAST_QUESTION_Result> GET_LAST_QUESTION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_LAST_QUESTION_Result>("GET_LAST_QUESTION");
        }
    
        public virtual ObjectResult<GET_LAST_TEST_Result> GET_LAST_TEST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_LAST_TEST_Result>("GET_LAST_TEST");
        }
    
        public virtual ObjectResult<GET_RESULT_WITH_APPLY_Result> GET_RESULT_WITH_APPLY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_RESULT_WITH_APPLY_Result>("GET_RESULT_WITH_APPLY");
        }
    }
}
